### ISSUE TITLE
Refactor Filtering class

### ISSUE THREAD

**Issue by khillion** [motleystate/moonstone#8]
## Description
Refactor `Filtering` and create as many filtering classes as method in it

## Additional information

`MeanFiltering` is a good example to follow

**Comment by khillion** [comment]
## TODO

- [ ] update base class as abstract classes
- [ ] create new classes from 4 different methods of the `Filtering` class:
  - [ ] `remove_data_without_metadata`
  - [ ] `remove_rows_without_relevant_info`
  - [ ] `selecting_rows`
  - [ ] `deleting_only_zeros_rows`
- [ ] Replace usage of `Filtering` in `main.py` and `differentialanalysis.py` part
- [ ] Delete `Filtering`
